// requiring modules for connections.
const dbConnect = require("./mongodb_connection");

const insert = async () => {
  const db = await dbConnect();
  // don't insert _id, as it is automatically generated by mongodb - insert data into mongodb.
  // insertOne() and insertMany() are query functions in mongodb.
  const result = await db.insertMany([
    {
      name: "note-5",
      brand: "vivo",
      price: 350,
      category: "mobile",
    },
    { name: "nord", brand: "oneplus", price: 450, category: "mobile" },
  ]);
  // the result will have attributes like acknowledged and insertID
  if (result.acknowledged) {
    console.log("Data has been inserted..");
  }
};

// function call
insert();
